### ISSUE TITLE
Decide how to organize tests

### ISSUE THREAD

**Issue by Soreloser2** [paulstn/SmarterTabSwitching#27]
Should we have all test code in a single file (something like test.js)?
Or have a main test folder with files each pertaining to different features?

Arguments for single file:
- All tests are easy to find
- Only need to run one script command, would never need to add extra args/files to a test runner
- No possibility of having related/repeated tests spread across multiple files/areas

Arguments for multiple files:
- There are easy ways to auto run tests with a single script if they share a naming convention (something like `test-(.*).js`)
- Separates areas of testing, from UI to backend to integration and different features
- Fewer merge conflict issues on multiple files

**Comment by paulstn** [comment]
I feel more inclined towards multiple files, because that would provide more atomic unit tests, as opposed to having all of the unit tests tangled up within one file. However, since this project is relatively small, we don't particularly need to do one or the other.

**Comment by Soreloser2** [comment]
We have decided to organize all tests in either "unit" or "integration", and then separate files for each feature/discernible testing area
